<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<Archive name="Root">
  <!--Grasshopper archive-->
  <!--Grasshopper and GH_IO.dll are copyrighted by Robert McNeel & Associates-->
  <!--Archive generated by GH_IO.dll file utility library {0.2.0002}-->
  <items count="1">
    <item name="ArchiveVersion" type_name="gh_version" type_code="80">
      <Major>0</Major>
      <Minor>2</Minor>
      <Revision>2</Revision>
    </item>
  </items>
  <chunks count="2">
    <chunk name="Definition">
      <items count="1">
        <item name="plugin_version" type_name="gh_version" type_code="80">
          <Major>1</Major>
          <Minor>0</Minor>
          <Revision>8</Revision>
        </item>
      </items>
      <chunks count="5">
        <chunk name="DocumentHeader">
          <items count="5">
            <item name="DocumentID" type_name="gh_guid" type_code="9">5d7f8748-9f47-496c-a34a-c4a5ce7820ea</item>
            <item name="Preview" type_name="gh_string" type_code="10">Shaded</item>
            <item name="PreviewMeshType" type_name="gh_int32" type_code="3">1</item>
            <item name="PreviewNormal" type_name="gh_drawing_color" type_code="36">
              <ARGB>100;150;0;0</ARGB>
            </item>
            <item name="PreviewSelected" type_name="gh_drawing_color" type_code="36">
              <ARGB>100;0;150;0</ARGB>
            </item>
          </items>
        </chunk>
        <chunk name="DefinitionProperties">
          <items count="4">
            <item name="Date" type_name="gh_date" type_code="8">1740552658270</item>
            <item name="Description" type_name="gh_string" type_code="10">Bicycle Fork generated by Spinlio</item>
            <item name="KeepOpen" type_name="gh_bool" type_code="1">false</item>
            <item name="Name" type_name="gh_string" type_code="10">Bicycle Fork.ghx</item>
          </items>
          <chunks count="3">
            <chunk name="Revisions">
              <items count="1">
                <item name="RevisionCount" type_name="gh_int32" type_code="3">0</item>
              </items>
            </chunk>
            <chunk name="Projection">
              <items count="2">
                <item name="Target" type_name="gh_drawing_point" type_code="30">
                  <X>-1367</X>
                  <Y>-125</Y>
                </item>
                <item name="Zoom" type_name="gh_single" type_code="5">1.4889727</item>
              </items>
            </chunk>
            <chunk name="Views">
              <items count="1">
                <item name="ViewCount" type_name="gh_int32" type_code="3">0</item>
              </items>
            </chunk>
          </chunks>
        </chunk><chunk name="DefinitionObjects"><items count="8">
    <item name="Object" type_name="gh_object" type_code="3">
      <GUID>53382daa-6f10-4962-a980-6178f4534f3d</GUID>
      <Name>Number</Name>
      <Attributes>
        <Bounds>
          <X>0</X>
          <Y>100</Y>
          <W>50</W>
          <H>20</H>
        </Bounds>
        <Pivot>
          <X>25</X>
          <Y>110</Y>
        </Pivot>
      </Attributes>
      <param_input index="0">
        <Name>steerer_length</Name>
        <Description>Parameter steerer_length</Description>
        <Value>150</Value>
        <TypeHint>System.Int32</TypeHint>
        <Access>1</Access> <!-- 1 = item access -->
      </param_input>
    </item>
    <item name="Object" type_name="gh_object" type_code="3">
      <GUID>01009522-4dbb-4efe-b9ba-82652137edb2</GUID>
      <Name>Number</Name>
      <Attributes>
        <Bounds>
          <X>150</X>
          <Y>100</Y>
          <W>50</W>
          <H>20</H>
        </Bounds>
        <Pivot>
          <X>175</X>
          <Y>110</Y>
        </Pivot>
      </Attributes>
      <param_input index="0">
        <Name>steerer_diameter</Name>
        <Description>Parameter steerer_diameter</Description>
        <Value>28.6</Value>
        <TypeHint>System.Double</TypeHint>
        <Access>1</Access> <!-- 1 = item access -->
      </param_input>
    </item>
    <item name="Object" type_name="gh_object" type_code="3">
      <GUID>db181a88-1cf6-4b52-9e6a-ae1a310049ba</GUID>
      <Name>Number</Name>
      <Attributes>
        <Bounds>
          <X>300</X>
          <Y>100</Y>
          <W>50</W>
          <H>20</H>
        </Bounds>
        <Pivot>
          <X>325</X>
          <Y>110</Y>
        </Pivot>
      </Attributes>
      <param_input index="0">
        <Name>crown_width</Name>
        <Description>Parameter crown_width</Description>
        <Value>60</Value>
        <TypeHint>System.Int32</TypeHint>
        <Access>1</Access> <!-- 1 = item access -->
      </param_input>
    </item>
    <item name="Object" type_name="gh_object" type_code="3">
      <GUID>6250aa81-d10f-498b-8479-2d30f32a5d1d</GUID>
      <Name>Number</Name>
      <Attributes>
        <Bounds>
          <X>450</X>
          <Y>100</Y>
          <W>50</W>
          <H>20</H>
        </Bounds>
        <Pivot>
          <X>475</X>
          <Y>110</Y>
        </Pivot>
      </Attributes>
      <param_input index="0">
        <Name>blade_length</Name>
        <Description>Parameter blade_length</Description>
        <Value>400</Value>
        <TypeHint>System.Int32</TypeHint>
        <Access>1</Access> <!-- 1 = item access -->
      </param_input>
    </item>
    <item name="Object" type_name="gh_object" type_code="3">
      <GUID>268435f4-4875-4bb4-87cb-0f38f3c29c94</GUID>
      <Name>Number</Name>
      <Attributes>
        <Bounds>
          <X>600</X>
          <Y>100</Y>
          <W>50</W>
          <H>20</H>
        </Bounds>
        <Pivot>
          <X>625</X>
          <Y>110</Y>
        </Pivot>
      </Attributes>
      <param_input index="0">
        <Name>dropout_width</Name>
        <Description>Parameter dropout_width</Description>
        <Value>100</Value>
        <TypeHint>System.Int32</TypeHint>
        <Access>1</Access> <!-- 1 = item access -->
      </param_input>
    </item>
    <item name="Object" type_name="gh_object" type_code="3">
      <GUID>7051ff76-9025-4450-a1f0-729fb14aeb3a</GUID>
      <Name>Number</Name>
      <Attributes>
        <Bounds>
          <X>750</X>
          <Y>100</Y>
          <W>50</W>
          <H>20</H>
        </Bounds>
        <Pivot>
          <X>775</X>
          <Y>110</Y>
        </Pivot>
      </Attributes>
      <param_input index="0">
        <Name>rake</Name>
        <Description>Parameter rake</Description>
        <Value>45</Value>
        <TypeHint>System.Int32</TypeHint>
        <Access>1</Access> <!-- 1 = item access -->
      </param_input>
    </item>
  <item name="Object" type_name="gh_object" type_code="3">
    <GUID>1d310969-8749-482d-962e-90b2678bfd74</GUID>
    <Name>Python Script</Name>
    <Attributes>
      <Bounds>
        <X>950</X>
        <Y>100</Y>
        <W>100</W>
        <H>100</H>
      </Bounds>
      <Pivot>
        <X>1000</X>
        <Y>150</Y>
      </Pivot>
    </Attributes>
    <param_input index="0">
      <Name>x</Name>
      <TypeHint>script</TypeHint>
      <Access>0</Access>
      <Data>
        <![CDATA[import Rhino.Geometry as rg
import scriptcontext as sc
import math

def create_fork(steerer_length, steerer_diameter, crown_width, blade_length, dropout_width, rake):
    # Create a new mesh
    mesh = rg.Mesh()
    
    # Steerer tube
    steerer_radius = steerer_diameter / 2
    tube = rg.Cylinder(
        rg.Circle(rg.Point3d(0, 0, 0), steerer_radius),
        steerer_length
    )
    steerer_mesh = rg.Mesh.CreateFromCylinder(tube, 12, 1)
    mesh.Append(steerer_mesh)
    
    # Crown
    crown_height = 20
    crown = rg.Box(
        rg.Plane.WorldXY,
        rg.Interval(-crown_width/2, crown_width/2),
        rg.Interval(-crown_height/2, crown_height/2),
        rg.Interval(-15, 15)
    )
    crown_mesh = rg.Mesh.CreateFromBox(crown, 2, 2, 2)
    crown_mesh.Translate(rg.Vector3d(0, 0, -crown_height/2))
    mesh.Append(crown_mesh)
    
    # Blades
    blade_radius = 12
    for side in [-1, 1]:
        # Start point at crown
        start = rg.Point3d(side * crown_width/2, 0, 0)
        # End point at dropout with rake
        end = rg.Point3d(side * dropout_width/2, blade_length, rake)
        
        # Create a line between start and end
        blade_line = rg.Line(start, end)
        
        # Create a pipe around the line
        blade_pipe = rg.Cylinder(
            rg.Circle(rg.Plane(start, rg.Vector3d(0,1,0)), blade_radius),
            blade_line.Length
        )
        blade_mesh = rg.Mesh.CreateFromCylinder(blade_pipe, 8, 1)
        
        # Rotate and translate to match the blade line
        angle = math.atan2(blade_line.Direction.Z, blade_line.Direction.Y)
        blade_mesh.Rotate(angle, rg.Vector3d(1,0,0), start)
        mesh.Append(blade_mesh)
    
    # Return the mesh
    return mesh

# Create the fork using the parameters
fork_mesh = create_fork(steerer_length, steerer_diameter, crown_width, blade_length, dropout_width, rake)

# Output the resulting mesh
a = fork_mesh]]>
      </Data>
    </param_input>
    <param_input index="1">
      <Name>steerer_length</Name>
      <TypeHint>double</TypeHint>
      <Access>2</Access> <!-- 2 = list access -->
    </param_input>
    <param_input index="2">
      <Name>steerer_diameter</Name>
      <TypeHint>double</TypeHint>
      <Access>2</Access> <!-- 2 = list access -->
    </param_input>
    <param_input index="3">
      <Name>crown_width</Name>
      <TypeHint>double</TypeHint>
      <Access>2</Access> <!-- 2 = list access -->
    </param_input>
    <param_input index="4">
      <Name>blade_length</Name>
      <TypeHint>double</TypeHint>
      <Access>2</Access> <!-- 2 = list access -->
    </param_input>
    <param_input index="5">
      <Name>dropout_width</Name>
      <TypeHint>double</TypeHint>
      <Access>2</Access> <!-- 2 = list access -->
    </param_input>
    <param_input index="6">
      <Name>rake</Name>
      <TypeHint>double</TypeHint>
      <Access>2</Access> <!-- 2 = list access -->
    </param_input>
    <param_output index="0">
      <Name>Out</Name>
      <Description>Script output</Description>
      <TypeHint>mesh</TypeHint>
    </param_output>
  </item>
  <item name="Object" type_name="gh_object" type_code="3">
    <GUID>b972603d-b98c-4803-a2ad-bbdd44e0b6e9</GUID>
    <Name>Bake</Name>
    <Attributes>
      <Bounds>
        <X>1100</X>
        <Y>100</Y>
        <W>80</W>
        <H>60</H>
      </Bounds>
      <Pivot>
        <X>1140</X>
        <Y>130</Y>
      </Pivot>
    </Attributes>
    <param_input index="0">
      <Name>Data</Name>
      <Description>Data to bake</Description>
      <SourceCount>1</SourceCount>
      <Source index="0">1d310969-8749-482d-962e-90b2678bfd74</Source>
      <TypeHint>auto</TypeHint>
      <Access>2</Access>
    </param_input>
  </item>
  </items>
  </chunk>
  <chunk name="DefinitionParametersList">
    <items count="0" />
  </chunk>
  </chunks>
  </chunk>
  <chunk name="Thumbnail">
    <items count="1">
      <item name="Thumbnail" type_name="gh_drawing_bitmap" type_code="37">
        <bitmap length="1000">
        <!-- Base64-encoded thumbnail would go here -->
        </bitmap>
      </item>
    </items>
  </chunk>
  </chunks>
</Archive>